// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace CsBindgen
{
    internal static unsafe partial class NativeMethods
    {
        const string __DllName = "rfe";





        /// <summary>
        ///  Returns whether the platform RF Explorer USB serial driver appears to be installed.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_is_driver_installed", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.U1)]
        internal static extern bool rfe_is_driver_installed();

        /// <summary>
        ///  Returns a heap-allocated array of RF Explorer serial port names.
        ///
        ///  If `len` is non-NULL, it is set to the number of returned names. The returned
        ///  array and each string in it are owned by the caller and must be released with
        ///  `rfe_free_port_names`.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_port_names", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte** rfe_port_names(nuint* len);

        /// <summary>
        ///  Frees an array returned by `rfe_port_names`.
        ///
        ///  `len` must be the same length returned by `rfe_port_names`. Passing `NULL`
        ///  is allowed and has no effect.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_free_port_names", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void rfe_free_port_names(byte** port_names_ptr, nuint len);

        /// <summary>
        ///  Gets one pixel from an RF Explorer LCD screen capture.
        ///
        ///  The top-left pixel is `(0, 0)` and the bottom-right pixel is `(127, 63)`.
        ///  On success, `pixel` is set to `true` for an enabled pixel and `false` for a
        ///  disabled pixel. Returns `RESULT_INVALID_INPUT_ERROR` if the coordinates are
        ///  out of range.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_screen_data_get_pixel", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Result rfe_screen_data_get_pixel(ScreenData* screen_data, byte x, byte y, bool* pixel);

        /// <summary>
        ///  Gets one pixel from an RF Explorer LCD screen capture with bounds checking.
        ///
        ///  This is equivalent to `rfe_screen_data_get_pixel`; both functions return
        ///  `RESULT_INVALID_INPUT_ERROR` for out-of-range coordinates.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_screen_data_get_pixel_checked", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Result rfe_screen_data_get_pixel_checked(ScreenData* screen_data, byte x, byte y, bool* pixel);

        /// <summary>
        ///  Writes the screen capture timestamp as Unix seconds.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_screen_data_timestamp", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Result rfe_screen_data_timestamp(ScreenData* screen_data, long* timestamp);

        /// <summary>
        ///  Frees screen data returned by an `rfe_*_screen_data` function.
        ///
        ///  Passing `NULL` is allowed and has no effect.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_screen_data_free", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void rfe_screen_data_free(ScreenData* screen_data);

        /// <summary>
        ///  Writes the display name of a signal generator model.
        ///
        ///  `name_buf` must point to a writable buffer of at least `len` bytes. The
        ///  buffer receives a null-terminated C string. Returns
        ///  `RESULT_INVALID_INPUT_ERROR` if `len` is too small.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_signal_generator_model_name", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Result rfe_signal_generator_model_name(SignalGeneratorModel model, byte* name_buf, nuint len);

        /// <summary>
        ///  Returns the model's minimum supported output frequency in hertz.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_signal_generator_model_min_freq_hz", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ulong rfe_signal_generator_model_min_freq_hz(SignalGeneratorModel model);

        /// <summary>
        ///  Returns the model's maximum supported output frequency in hertz.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_signal_generator_model_max_freq_hz", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ulong rfe_signal_generator_model_max_freq_hz(SignalGeneratorModel model);

        /// <summary>
        ///  Connects to the first RF Explorer signal generator found on a CP210x USB serial port.
        ///
        ///  Returns `NULL` if no compatible device can be opened and initialized. The
        ///  returned pointer is owned by the caller and must be freed with
        ///  `rfe_signal_generator_free`.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_signal_generator_connect", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern SignalGenerator* rfe_signal_generator_connect();

        /// <summary>
        ///  Connects to a named serial port using the given baud rate.
        ///
        ///  `name` must be a valid null-terminated UTF-8 string. Returns `NULL` if the
        ///  pointer is null, the string is invalid, or the device cannot be opened and
        ///  initialized. The returned pointer is owned by the caller and must be freed
        ///  with `rfe_signal_generator_free`.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_signal_generator_connect_with_name_and_baud_rate", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern SignalGenerator* rfe_signal_generator_connect_with_name_and_baud_rate(byte* name, uint baud_rate);

        /// <summary>
        ///  Frees a signal generator returned by `rfe_signal_generator_connect`.
        ///
        ///  Passing `NULL` is allowed and has no effect.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_signal_generator_free", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void rfe_signal_generator_free(SignalGenerator* rfe);

        /// <summary>
        ///  Sends raw bytes to the signal generator.
        ///
        ///  `bytes` must point to at least `len` bytes. This function is primarily for
        ///  advanced users that need to send RF Explorer commands not wrapped by this API.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_signal_generator_send_bytes", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Result rfe_signal_generator_send_bytes(SignalGenerator* rfe, byte* bytes, nuint len);

        /// <summary>
        ///  Writes the connected serial port name to a caller-provided buffer.
        ///
        ///  Use `rfe_signal_generator_port_name_len` to get the required buffer size,
        ///  including the terminating null byte.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_signal_generator_port_name", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Result rfe_signal_generator_port_name(SignalGenerator* rfe, byte* port_name_buf, nuint buf_len);

        /// <summary>
        ///  Returns the buffer size required for `rfe_signal_generator_port_name`.
        ///
        ///  The returned size includes the terminating null byte. Returns zero if `rfe`
        ///  is `NULL`.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_signal_generator_port_name_len", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern nuint rfe_signal_generator_port_name_len(SignalGenerator* rfe);

        /// <summary>
        ///  Writes the firmware version to a caller-provided buffer.
        ///
        ///  Use `rfe_signal_generator_firmware_version_len` to get the required buffer
        ///  size, including the terminating null byte.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_signal_generator_firmware_version", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Result rfe_signal_generator_firmware_version(SignalGenerator* rfe, byte* firmware_version_buf, nuint buf_len);

        /// <summary>
        ///  Returns the buffer size required for `rfe_signal_generator_firmware_version`.
        ///
        ///  The returned size includes the terminating null byte. Returns zero if `rfe`
        ///  is `NULL`.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_signal_generator_firmware_version_len", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern nuint rfe_signal_generator_firmware_version_len(SignalGenerator* rfe);

        /// <summary>
        ///  Writes the device serial number to a caller-provided buffer.
        ///
        ///  Use `rfe_signal_generator_serial_number_len` to get the required buffer
        ///  size, including the terminating null byte. Returns `RESULT_NO_DATA` if the
        ///  device does not report a serial number.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_signal_generator_serial_number", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Result rfe_signal_generator_serial_number(SignalGenerator* rfe, byte* serial_number_buf, nuint buf_len);

        /// <summary>
        ///  Returns the buffer size required for `rfe_signal_generator_serial_number`.
        ///
        ///  The returned size includes the terminating null byte. Returns zero if `rfe`
        ///  is `NULL` or no serial number has been received.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_signal_generator_serial_number_len", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern nuint rfe_signal_generator_serial_number_len(SignalGenerator* rfe);

        /// <summary>
        ///  Turns the signal generator LCD on.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_signal_generator_lcd_on", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Result rfe_signal_generator_lcd_on(SignalGenerator* rfe);

        /// <summary>
        ///  Turns the signal generator LCD off.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_signal_generator_lcd_off", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Result rfe_signal_generator_lcd_off(SignalGenerator* rfe);

        /// <summary>
        ///  Enables screen dump messages from the signal generator.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_signal_generator_enable_dump_screen", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Result rfe_signal_generator_enable_dump_screen(SignalGenerator* rfe);

        /// <summary>
        ///  Disables screen dump messages from the signal generator.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_signal_generator_disable_dump_screen", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Result rfe_signal_generator_disable_dump_screen(SignalGenerator* rfe);

        /// <summary>
        ///  Holds the current signal generator operation.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_signal_generator_hold", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Result rfe_signal_generator_hold(SignalGenerator* rfe);

        /// <summary>
        ///  Reboots the signal generator.
        ///
        ///  The `rfe` pointer must not be used after a successful reboot unless the
        ///  device is reconnected.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_signal_generator_reboot", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Result rfe_signal_generator_reboot(SignalGenerator* rfe);

        /// <summary>
        ///  Powers off the signal generator.
        ///
        ///  The `rfe` pointer must not be used after a successful power-off unless the
        ///  device is reconnected.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_signal_generator_power_off", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Result rfe_signal_generator_power_off(SignalGenerator* rfe);

        /// <summary>
        ///  Writes the most recent main signal generator configuration to `config`.
        ///
        ///  Returns `RESULT_NO_DATA` if no matching configuration has been received.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_signal_generator_config", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Result rfe_signal_generator_config(SignalGenerator* rfe, SignalGeneratorConfig* config);

        /// <summary>
        ///  Writes the most recent amplitude sweep configuration to `config`.
        ///
        ///  Returns `RESULT_NO_DATA` if no matching configuration has been received.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_signal_generator_config_amp_sweep", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Result rfe_signal_generator_config_amp_sweep(SignalGenerator* rfe, SignalGeneratorConfigAmpSweep* config);

        /// <summary>
        ///  Writes the most recent CW configuration to `config`.
        ///
        ///  Returns `RESULT_NO_DATA` if no matching configuration has been received.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_signal_generator_config_cw", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Result rfe_signal_generator_config_cw(SignalGenerator* rfe, SignalGeneratorConfigCw* config);

        /// <summary>
        ///  Writes the most recent frequency sweep configuration to `config`.
        ///
        ///  Returns `RESULT_NO_DATA` if no matching configuration has been received.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_signal_generator_config_freq_sweep", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Result rfe_signal_generator_config_freq_sweep(SignalGenerator* rfe, SignalGeneratorConfigFreqSweep* config);

        /// <summary>
        ///  Returns the most recent LCD screen capture.
        ///
        ///  On success, `screen_data` receives a heap-allocated `ScreenData` pointer
        ///  owned by the caller. Free it with `rfe_screen_data_free`.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_signal_generator_screen_data", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Result rfe_signal_generator_screen_data(SignalGenerator* rfe, ScreenData** screen_data);

        /// <summary>
        ///  Waits for the next LCD screen capture.
        ///
        ///  On success, `screen_data` receives a heap-allocated `ScreenData` pointer
        ///  owned by the caller. Free it with `rfe_screen_data_free`.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_signal_generator_wait_for_next_screen_data", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Result rfe_signal_generator_wait_for_next_screen_data(SignalGenerator* rfe, ScreenData** screen_data);

        /// <summary>
        ///  Waits up to `timeout_secs` seconds for the next LCD screen capture.
        ///
        ///  On success, `screen_data` receives a heap-allocated `ScreenData` pointer
        ///  owned by the caller. Free it with `rfe_screen_data_free`.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_signal_generator_wait_for_next_screen_data_with_timeout", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Result rfe_signal_generator_wait_for_next_screen_data_with_timeout(SignalGenerator* rfe, ulong timeout_secs, ScreenData** screen_data);

        /// <summary>
        ///  Writes the most recent temperature range to `temperature`.
        ///
        ///  Returns `RESULT_NO_DATA` if the device has not reported a temperature range.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_signal_generator_temperature", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Result rfe_signal_generator_temperature(SignalGenerator* rfe, Temperature* temperature);

        /// <summary>
        ///  Writes the main radio module model to `model`.
        ///
        ///  Returns `RESULT_NO_DATA` if no main model has been reported.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_signal_generator_main_radio_model", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Result rfe_signal_generator_main_radio_model(SignalGenerator* rfe, SignalGeneratorModel* model);

        /// <summary>
        ///  Writes the expansion radio module model to `model`.
        ///
        ///  Returns `RESULT_NO_DATA` if no expansion model has been reported.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_signal_generator_expansion_radio_model", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Result rfe_signal_generator_expansion_radio_model(SignalGenerator* rfe, SignalGeneratorModel* model);

        /// <summary>
        ///  Writes the currently active radio module model to `model`.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_signal_generator_active_radio_model", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Result rfe_signal_generator_active_radio_model(SignalGenerator* rfe, SignalGeneratorModel* model);

        /// <summary>
        ///  Writes the currently inactive radio module model to `model`.
        ///
        ///  Returns `RESULT_NO_DATA` if no inactive model exists.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_signal_generator_inactive_radio_model", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Result rfe_signal_generator_inactive_radio_model(SignalGenerator* rfe, SignalGeneratorModel* model);

        /// <summary>
        ///  Starts amplitude sweep mode.
        ///
        ///  `cw_hz` is the CW frequency in hertz and `step_delay_sec` is the delay
        ///  between amplitude sweep steps in seconds.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_signal_generator_start_amp_sweep", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Result rfe_signal_generator_start_amp_sweep(SignalGenerator* rfe, ulong cw_hz, Attenuation start_attenuation, PowerLevel start_power_level, Attenuation stop_attenuation, PowerLevel stop_power_level, byte step_delay_sec);

        /// <summary>
        ///  Starts amplitude sweep mode using the expansion module.
        ///
        ///  `cw_hz` is the CW frequency in hertz and `step_delay_sec` is the delay
        ///  between amplitude sweep steps in seconds.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_signal_generator_start_amp_sweep_exp", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Result rfe_signal_generator_start_amp_sweep_exp(SignalGenerator* rfe, ulong cw_hz, double start_power_dbm, double step_power_db, double stop_power_dbm, byte step_delay_sec);

        /// <summary>
        ///  Starts CW mode.
        ///
        ///  `cw_hz` is the CW frequency in hertz.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_signal_generator_start_cw", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Result rfe_signal_generator_start_cw(SignalGenerator* rfe, ulong cw_hz, Attenuation attenuation, PowerLevel power_level);

        /// <summary>
        ///  Starts CW mode using the expansion module.
        ///
        ///  `cw_hz` is the CW frequency in hertz.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_signal_generator_start_cw_exp", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Result rfe_signal_generator_start_cw_exp(SignalGenerator* rfe, ulong cw_hz, double power_dbm);

        /// <summary>
        ///  Starts frequency sweep mode.
        ///
        ///  Frequencies are represented in hertz and `step_delay_sec` is the delay
        ///  between frequency sweep steps in seconds.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_signal_generator_start_freq_sweep", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Result rfe_signal_generator_start_freq_sweep(SignalGenerator* rfe, ulong start_hz, Attenuation attenuation, PowerLevel power_level, ushort sweep_steps, ulong step_hz, byte step_delay_sec);

        /// <summary>
        ///  Starts frequency sweep mode using the expansion module.
        ///
        ///  Frequencies are represented in hertz and `step_delay_sec` is the delay
        ///  between frequency sweep steps in seconds.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_signal_generator_start_freq_sweep_exp", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Result rfe_signal_generator_start_freq_sweep_exp(SignalGenerator* rfe, ulong start_hz, double power_dbm, ushort sweep_steps, ulong step_hz, byte step_delay_sec);

        /// <summary>
        ///  Starts tracking mode.
        ///
        ///  `start_hz` and `step_hz` are represented in hertz.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_signal_generator_start_tracking", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Result rfe_signal_generator_start_tracking(SignalGenerator* rfe, ulong start_hz, Attenuation attenuation, PowerLevel power_level, ushort sweep_steps, ulong step_hz);

        /// <summary>
        ///  Starts tracking mode using the expansion module.
        ///
        ///  `start_hz` and `step_hz` are represented in hertz.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_signal_generator_start_tracking_exp", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Result rfe_signal_generator_start_tracking_exp(SignalGenerator* rfe, ulong start_hz, double power_dbm, ushort sweep_steps, ulong step_hz);

        /// <summary>
        ///  Jumps to a new frequency using the tracking step frequency.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_signal_generator_tracking_step", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Result rfe_signal_generator_tracking_step(SignalGenerator* rfe, ushort steps);

        /// <summary>
        ///  Sets the callback called when the main signal generator configuration is received.
        ///
        ///  The callback may be invoked from a background thread, and multiple callback
        ///  invocations may overlap. `user_data`, if non-NULL, must remain valid until
        ///  the callback is removed or the signal generator is freed.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_signal_generator_set_config_callback", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void rfe_signal_generator_set_config_callback(SignalGenerator* rfe, delegate* unmanaged[Cdecl]<SignalGeneratorConfig, void*, void> callback, void* user_data);

        /// <summary>
        ///  Removes the main configuration callback.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_signal_generator_remove_config_callback", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void rfe_signal_generator_remove_config_callback(SignalGenerator* rfe);

        /// <summary>
        ///  Sets the callback called when an amplitude sweep configuration is received.
        ///
        ///  The callback may be invoked from a background thread, and multiple callback
        ///  invocations may overlap. `user_data`, if non-NULL, must remain valid until
        ///  the callback is removed or the signal generator is freed.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_signal_generator_set_config_amp_sweep_callback", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void rfe_signal_generator_set_config_amp_sweep_callback(SignalGenerator* rfe, delegate* unmanaged[Cdecl]<SignalGeneratorConfigAmpSweep, void*, void> callback, void* user_data);

        /// <summary>
        ///  Removes the amplitude sweep configuration callback.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_signal_generator_remove_config_amp_sweep_callback", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void rfe_signal_generator_remove_config_amp_sweep_callback(SignalGenerator* rfe);

        /// <summary>
        ///  Sets the callback called when a CW configuration is received.
        ///
        ///  The callback may be invoked from a background thread, and multiple callback
        ///  invocations may overlap. `user_data`, if non-NULL, must remain valid until
        ///  the callback is removed or the signal generator is freed.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_signal_generator_set_config_cw_callback", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void rfe_signal_generator_set_config_cw_callback(SignalGenerator* rfe, delegate* unmanaged[Cdecl]<SignalGeneratorConfigCw, void*, void> callback, void* user_data);

        /// <summary>
        ///  Removes the CW configuration callback.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_signal_generator_remove_config_cw_callback", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void rfe_signal_generator_remove_config_cw_callback(SignalGenerator* rfe);

        /// <summary>
        ///  Sets the callback called when a frequency sweep configuration is received.
        ///
        ///  The callback may be invoked from a background thread, and multiple callback
        ///  invocations may overlap. `user_data`, if non-NULL, must remain valid until
        ///  the callback is removed or the signal generator is freed.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_signal_generator_set_config_freq_sweep_callback", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void rfe_signal_generator_set_config_freq_sweep_callback(SignalGenerator* rfe, delegate* unmanaged[Cdecl]<SignalGeneratorConfigFreqSweep, void*, void> callback, void* user_data);

        /// <summary>
        ///  Removes the frequency sweep configuration callback.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_signal_generator_remove_config_freq_sweep_callback", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void rfe_signal_generator_remove_config_freq_sweep_callback(SignalGenerator* rfe);

        /// <summary>
        ///  Turns RF output power on.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_signal_generator_rf_power_on", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Result rfe_signal_generator_rf_power_on(SignalGenerator* rfe);

        /// <summary>
        ///  Turns RF output power off.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_signal_generator_rf_power_off", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Result rfe_signal_generator_rf_power_off(SignalGenerator* rfe);

        /// <summary>
        ///  Writes the display name of a spectrum analyzer model.
        ///
        ///  `name_buf` must point to a writable buffer of at least `len` bytes. The
        ///  buffer receives a null-terminated C string. Returns
        ///  `RESULT_INVALID_INPUT_ERROR` if `len` is too small or `model` is invalid.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_spectrum_analyzer_model_name", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Result rfe_spectrum_analyzer_model_name(SpectrumAnalyzerModel model, byte* name_buf, nuint len);

        /// <summary>
        ///  Returns whether the model supports Plus-model features.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_spectrum_analyzer_model_is_plus_model", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.U1)]
        internal static extern bool rfe_spectrum_analyzer_model_is_plus_model(SpectrumAnalyzerModel model);

        /// <summary>
        ///  Returns whether the model supports Wi-Fi analyzer mode.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_spectrum_analyzer_model_has_wifi_analyzer", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.U1)]
        internal static extern bool rfe_spectrum_analyzer_model_has_wifi_analyzer(SpectrumAnalyzerModel model);

        /// <summary>
        ///  Returns the model's minimum supported input frequency in hertz.
        ///
        ///  Returns zero if `model` is invalid.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_spectrum_analyzer_model_min_freq_hz", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ulong rfe_spectrum_analyzer_model_min_freq_hz(SpectrumAnalyzerModel model);

        /// <summary>
        ///  Returns the model's maximum supported input frequency in hertz.
        ///
        ///  Returns zero if `model` is invalid.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_spectrum_analyzer_model_max_freq_hz", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ulong rfe_spectrum_analyzer_model_max_freq_hz(SpectrumAnalyzerModel model);

        /// <summary>
        ///  Returns the model's minimum supported sweep span in hertz.
        ///
        ///  Returns zero if `model` is invalid.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_spectrum_analyzer_model_min_span_hz", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ulong rfe_spectrum_analyzer_model_min_span_hz(SpectrumAnalyzerModel model);

        /// <summary>
        ///  Returns the model's maximum supported sweep span in hertz.
        ///
        ///  Returns zero if `model` is invalid.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_spectrum_analyzer_model_max_span_hz", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ulong rfe_spectrum_analyzer_model_max_span_hz(SpectrumAnalyzerModel model);

        /// <summary>
        ///  Connects to the first RF Explorer spectrum analyzer found on a CP210x USB serial port.
        ///
        ///  Returns `NULL` if no compatible device can be opened and initialized. The
        ///  returned pointer is owned by the caller and must be freed with
        ///  `rfe_spectrum_analyzer_free`.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_spectrum_analyzer_connect", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern SpectrumAnalyzer* rfe_spectrum_analyzer_connect();

        /// <summary>
        ///  Connects to a named serial port using the given baud rate.
        ///
        ///  `name` must be a valid null-terminated UTF-8 string. Returns `NULL` if the
        ///  pointer is null, the string is invalid, or the device cannot be opened and
        ///  initialized. The returned pointer is owned by the caller and must be freed
        ///  with `rfe_spectrum_analyzer_free`.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_spectrum_analyzer_connect_with_name_and_baud_rate", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern SpectrumAnalyzer* rfe_spectrum_analyzer_connect_with_name_and_baud_rate(byte* name, uint baud_rate);

        /// <summary>
        ///  Frees a spectrum analyzer returned by `rfe_spectrum_analyzer_connect`.
        ///
        ///  Passing `NULL` is allowed and has no effect.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_spectrum_analyzer_free", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void rfe_spectrum_analyzer_free(SpectrumAnalyzer* rfe);

        /// <summary>
        ///  Sends raw bytes to the spectrum analyzer.
        ///
        ///  `bytes` must point to at least `len` bytes. This function is primarily for
        ///  advanced users that need to send RF Explorer commands not wrapped by this API.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_spectrum_analyzer_send_bytes", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Result rfe_spectrum_analyzer_send_bytes(SpectrumAnalyzer* rfe, byte* bytes, nuint len);

        /// <summary>
        ///  Writes the connected serial port name to a caller-provided buffer.
        ///
        ///  Use `rfe_spectrum_analyzer_port_name_len` to get the required buffer size,
        ///  including the terminating null byte.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_spectrum_analyzer_port_name", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Result rfe_spectrum_analyzer_port_name(SpectrumAnalyzer* rfe, byte* port_name_buf, nuint buf_len);

        /// <summary>
        ///  Returns the buffer size required for `rfe_spectrum_analyzer_port_name`.
        ///
        ///  The returned size includes the terminating null byte. Returns zero if `rfe`
        ///  is `NULL`.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_spectrum_analyzer_port_name_len", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern nuint rfe_spectrum_analyzer_port_name_len(SpectrumAnalyzer* rfe);

        /// <summary>
        ///  Writes the firmware version to a caller-provided buffer.
        ///
        ///  Use `rfe_spectrum_analyzer_firmware_version_len` to get the required buffer
        ///  size, including the terminating null byte.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_spectrum_analyzer_firmware_version", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Result rfe_spectrum_analyzer_firmware_version(SpectrumAnalyzer* rfe, byte* firmware_version_buf, nuint buf_len);

        /// <summary>
        ///  Returns the buffer size required for `rfe_spectrum_analyzer_firmware_version`.
        ///
        ///  The returned size includes the terminating null byte. Returns zero if `rfe`
        ///  is `NULL`.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_spectrum_analyzer_firmware_version_len", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern nuint rfe_spectrum_analyzer_firmware_version_len(SpectrumAnalyzer* rfe);

        /// <summary>
        ///  Writes the device serial number to a caller-provided buffer.
        ///
        ///  Use `rfe_spectrum_analyzer_serial_number_len` to get the required buffer
        ///  size, including the terminating null byte. Returns `RESULT_NO_DATA` if the
        ///  device does not report a serial number.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_spectrum_analyzer_serial_number", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Result rfe_spectrum_analyzer_serial_number(SpectrumAnalyzer* rfe, byte* serial_number_buf, nuint buf_len);

        /// <summary>
        ///  Returns the buffer size required for `rfe_spectrum_analyzer_serial_number`.
        ///
        ///  The returned size includes the terminating null byte. Returns zero if `rfe`
        ///  is `NULL` or no serial number has been received.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_spectrum_analyzer_serial_number_len", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern nuint rfe_spectrum_analyzer_serial_number_len(SpectrumAnalyzer* rfe);

        /// <summary>
        ///  Turns the spectrum analyzer LCD on.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_spectrum_analyzer_lcd_on", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Result rfe_spectrum_analyzer_lcd_on(SpectrumAnalyzer* rfe);

        /// <summary>
        ///  Turns the spectrum analyzer LCD off.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_spectrum_analyzer_lcd_off", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Result rfe_spectrum_analyzer_lcd_off(SpectrumAnalyzer* rfe);

        /// <summary>
        ///  Enables screen dump messages from the spectrum analyzer.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_spectrum_analyzer_enable_dump_screen", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Result rfe_spectrum_analyzer_enable_dump_screen(SpectrumAnalyzer* rfe);

        /// <summary>
        ///  Disables screen dump messages from the spectrum analyzer.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_spectrum_analyzer_disable_dump_screen", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Result rfe_spectrum_analyzer_disable_dump_screen(SpectrumAnalyzer* rfe);

        /// <summary>
        ///  Holds the current spectrum analyzer sweep.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_spectrum_analyzer_hold", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Result rfe_spectrum_analyzer_hold(SpectrumAnalyzer* rfe);

        /// <summary>
        ///  Reboots the spectrum analyzer.
        ///
        ///  The `rfe` pointer must not be used after a successful reboot unless the
        ///  device is reconnected.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_spectrum_analyzer_reboot", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Result rfe_spectrum_analyzer_reboot(SpectrumAnalyzer* rfe);

        /// <summary>
        ///  Powers off the spectrum analyzer.
        ///
        ///  The `rfe` pointer must not be used after a successful power-off unless the
        ///  device is reconnected.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_spectrum_analyzer_power_off", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Result rfe_spectrum_analyzer_power_off(SpectrumAnalyzer* rfe);

        /// <summary>
        ///  Returns the current sweep start frequency in hertz.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_spectrum_analyzer_start_freq_hz", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ulong rfe_spectrum_analyzer_start_freq_hz(SpectrumAnalyzer* rfe);

        /// <summary>
        ///  Returns the current sweep step size in hertz.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_spectrum_analyzer_step_size_hz", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ulong rfe_spectrum_analyzer_step_size_hz(SpectrumAnalyzer* rfe);

        /// <summary>
        ///  Returns the current sweep stop frequency in hertz.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_spectrum_analyzer_stop_freq_hz", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ulong rfe_spectrum_analyzer_stop_freq_hz(SpectrumAnalyzer* rfe);

        /// <summary>
        ///  Returns the current sweep center frequency in hertz.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_spectrum_analyzer_center_freq_hz", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ulong rfe_spectrum_analyzer_center_freq_hz(SpectrumAnalyzer* rfe);

        /// <summary>
        ///  Returns the current sweep span in hertz.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_spectrum_analyzer_span_hz", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ulong rfe_spectrum_analyzer_span_hz(SpectrumAnalyzer* rfe);

        /// <summary>
        ///  Returns the active radio module's minimum supported frequency in hertz.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_spectrum_analyzer_min_freq_hz", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ulong rfe_spectrum_analyzer_min_freq_hz(SpectrumAnalyzer* rfe);

        /// <summary>
        ///  Returns the active radio module's maximum supported frequency in hertz.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_spectrum_analyzer_max_freq_hz", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ulong rfe_spectrum_analyzer_max_freq_hz(SpectrumAnalyzer* rfe);

        /// <summary>
        ///  Returns the active radio module's maximum supported span in hertz.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_spectrum_analyzer_max_span_hz", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ulong rfe_spectrum_analyzer_max_span_hz(SpectrumAnalyzer* rfe);

        /// <summary>
        ///  Returns the resolution bandwidth in hertz.
        ///
        ///  Returns zero if the device has not reported a resolution bandwidth.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_spectrum_analyzer_rbw_hz", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ulong rfe_spectrum_analyzer_rbw_hz(SpectrumAnalyzer* rfe);

        /// <summary>
        ///  Returns the bottom displayed amplitude in dBm.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_spectrum_analyzer_min_amp_dbm", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern short rfe_spectrum_analyzer_min_amp_dbm(SpectrumAnalyzer* rfe);

        /// <summary>
        ///  Returns the top displayed amplitude in dBm.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_spectrum_analyzer_max_amp_dbm", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern short rfe_spectrum_analyzer_max_amp_dbm(SpectrumAnalyzer* rfe);

        /// <summary>
        ///  Returns the amplitude offset in dB.
        ///
        ///  Returns zero if the device has not reported an amplitude offset.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_spectrum_analyzer_amp_offset_db", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern sbyte rfe_spectrum_analyzer_amp_offset_db(SpectrumAnalyzer* rfe);

        /// <summary>
        ///  Returns the number of points in each sweep.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_spectrum_analyzer_sweep_len", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ushort rfe_spectrum_analyzer_sweep_len(SpectrumAnalyzer* rfe);

        /// <summary>
        ///  Returns the current operating mode.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_spectrum_analyzer_mode", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Mode rfe_spectrum_analyzer_mode(SpectrumAnalyzer* rfe);

        /// <summary>
        ///  Returns the current calculator mode.
        ///
        ///  Returns the enum default if the device has not reported a calculator mode.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_spectrum_analyzer_calc_mode", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern CalcMode rfe_spectrum_analyzer_calc_mode(SpectrumAnalyzer* rfe);

        /// <summary>
        ///  Copies the most recent sweep into a caller-provided buffer.
        ///
        ///  `sweep_buf` must point to at least `buf_len` `float` values. If `sweep_len`
        ///  is non-NULL, it is set to the number of values written. Returns
        ///  `RESULT_INVALID_INPUT_ERROR` if the buffer is too small, or `RESULT_NO_DATA`
        ///  if no sweep has been received.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_spectrum_analyzer_sweep", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Result rfe_spectrum_analyzer_sweep(SpectrumAnalyzer* rfe, float* sweep_buf, nuint buf_len, nuint* sweep_len);

        /// <summary>
        ///  Waits for the next sweep and copies it into a caller-provided buffer.
        ///
        ///  `sweep_buf` must point to at least `buf_len` `float` values. If `sweep_len`
        ///  is non-NULL, it is set to the number of values written.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_spectrum_analyzer_wait_for_next_sweep", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Result rfe_spectrum_analyzer_wait_for_next_sweep(SpectrumAnalyzer* rfe, float* sweep_buf, nuint buf_len, nuint* sweep_len);

        /// <summary>
        ///  Waits up to `timeout_secs` seconds for the next sweep and copies it into a buffer.
        ///
        ///  `sweep_buf` must point to at least `buf_len` `float` values. If `sweep_len`
        ///  is non-NULL, it is set to the number of values written.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_spectrum_analyzer_wait_for_next_sweep_with_timeout", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Result rfe_spectrum_analyzer_wait_for_next_sweep_with_timeout(SpectrumAnalyzer* rfe, ulong timeout_secs, float* sweep_buf, nuint buf_len, nuint* sweep_len);

        /// <summary>
        ///  Returns the most recent LCD screen capture.
        ///
        ///  On success, `screen_data` receives a heap-allocated `ScreenData` pointer
        ///  owned by the caller. Free it with `rfe_screen_data_free`.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_spectrum_analyzer_screen_data", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Result rfe_spectrum_analyzer_screen_data(SpectrumAnalyzer* rfe, ScreenData** screen_data);

        /// <summary>
        ///  Waits for the next LCD screen capture.
        ///
        ///  On success, `screen_data` receives a heap-allocated `ScreenData` pointer
        ///  owned by the caller. Free it with `rfe_screen_data_free`.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_spectrum_analyzer_wait_for_next_screen_data", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Result rfe_spectrum_analyzer_wait_for_next_screen_data(SpectrumAnalyzer* rfe, ScreenData** screen_data);

        /// <summary>
        ///  Waits up to `timeout_secs` seconds for the next LCD screen capture.
        ///
        ///  On success, `screen_data` receives a heap-allocated `ScreenData` pointer
        ///  owned by the caller. Free it with `rfe_screen_data_free`.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_spectrum_analyzer_wait_for_next_screen_data_with_timeout", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Result rfe_spectrum_analyzer_wait_for_next_screen_data_with_timeout(SpectrumAnalyzer* rfe, ulong timeout_secs, ScreenData** screen_data);

        /// <summary>
        ///  Writes the current DSP mode to `dsp_mode`.
        ///
        ///  Returns `RESULT_NO_DATA` if the device has not reported a DSP mode.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_spectrum_analyzer_dsp_mode", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Result rfe_spectrum_analyzer_dsp_mode(SpectrumAnalyzer* rfe, DspMode* dsp_mode);

        /// <summary>
        ///  Writes the current tracking status to `tracking_status`.
        ///
        ///  Returns `RESULT_NO_DATA` if the device has not reported a tracking status.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_spectrum_analyzer_tracking_status", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Result rfe_spectrum_analyzer_tracking_status(SpectrumAnalyzer* rfe, TrackingStatus* tracking_status);

        /// <summary>
        ///  Writes the current input stage to `input_stage`.
        ///
        ///  Returns `RESULT_NO_DATA` if the device has not reported an input stage.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_spectrum_analyzer_input_stage", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Result rfe_spectrum_analyzer_input_stage(SpectrumAnalyzer* rfe, InputStage* input_stage);

        /// <summary>
        ///  Returns the main radio module model.
        ///
        ///  Returns `SPECTRUM_ANALYZER_MODEL_UNKNOWN` if no model has been reported.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_spectrum_analyzer_main_radio_model", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern SpectrumAnalyzerModel rfe_spectrum_analyzer_main_radio_model(SpectrumAnalyzer* rfe);

        /// <summary>
        ///  Returns the expansion radio module model.
        ///
        ///  Returns `SPECTRUM_ANALYZER_MODEL_UNKNOWN` if no expansion model has been reported.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_spectrum_analyzer_expansion_radio_model", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern SpectrumAnalyzerModel rfe_spectrum_analyzer_expansion_radio_model(SpectrumAnalyzer* rfe);

        /// <summary>
        ///  Returns the currently active radio module model.
        ///
        ///  Returns `SPECTRUM_ANALYZER_MODEL_UNKNOWN` if no model has been reported.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_spectrum_analyzer_active_radio_model", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern SpectrumAnalyzerModel rfe_spectrum_analyzer_active_radio_model(SpectrumAnalyzer* rfe);

        /// <summary>
        ///  Returns the currently inactive radio module model.
        ///
        ///  Returns `SPECTRUM_ANALYZER_MODEL_UNKNOWN` if no inactive model exists.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_spectrum_analyzer_inactive_radio_model", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern SpectrumAnalyzerModel rfe_spectrum_analyzer_inactive_radio_model(SpectrumAnalyzer* rfe);

        /// <summary>
        ///  Starts Wi-Fi analyzer mode for the requested Wi-Fi band.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_spectrum_analyzer_start_wifi_analyzer", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Result rfe_spectrum_analyzer_start_wifi_analyzer(SpectrumAnalyzer* rfe, WifiBand wifi_band);

        /// <summary>
        ///  Stops Wi-Fi analyzer mode.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_spectrum_analyzer_stop_wifi_analyzer", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Result rfe_spectrum_analyzer_stop_wifi_analyzer(SpectrumAnalyzer* rfe);

        /// <summary>
        ///  Requests tracking mode and waits for a tracking status response.
        ///
        ///  `start_hz` is the tracking start frequency in hertz and `step_hz` is the
        ///  tracking step frequency in hertz.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_spectrum_analyzer_request_tracking", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Result rfe_spectrum_analyzer_request_tracking(SpectrumAnalyzer* rfe, ulong start_hz, ulong step_hz);

        /// <summary>
        ///  Steps over the tracking step frequency and makes a measurement.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_spectrum_analyzer_tracking_step", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Result rfe_spectrum_analyzer_tracking_step(SpectrumAnalyzer* rfe, ushort step);

        /// <summary>
        ///  Sets the sweep start and stop frequencies in hertz.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_spectrum_analyzer_set_start_stop", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Result rfe_spectrum_analyzer_set_start_stop(SpectrumAnalyzer* rfe, ulong start_hz, ulong stop_hz);

        /// <summary>
        ///  Sets the sweep start frequency, stop frequency, and number of sweep points.
        ///
        ///  Frequencies are represented in hertz.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_spectrum_analyzer_set_start_stop_sweep_len", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Result rfe_spectrum_analyzer_set_start_stop_sweep_len(SpectrumAnalyzer* rfe, ulong start_hz, ulong stop_hz, ushort sweep_len);

        /// <summary>
        ///  Sets the sweep center frequency and span in hertz.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_spectrum_analyzer_set_center_span", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Result rfe_spectrum_analyzer_set_center_span(SpectrumAnalyzer* rfe, ulong center_hz, ulong span_hz);

        /// <summary>
        ///  Sets the sweep center frequency, span, and number of sweep points.
        ///
        ///  Frequencies are represented in hertz.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_spectrum_analyzer_set_center_span_sweep_len", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Result rfe_spectrum_analyzer_set_center_span_sweep_len(SpectrumAnalyzer* rfe, ulong center_hz, ulong span_hz, ushort sweep_len);

        /// <summary>
        ///  Sets the minimum and maximum amplitudes displayed on the RF Explorer screen.
        ///
        ///  Amplitudes are represented in dBm.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_spectrum_analyzer_set_min_max_amps", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Result rfe_spectrum_analyzer_set_min_max_amps(SpectrumAnalyzer* rfe, short min_amp_dbm, short max_amp_dbm);

        /// <summary>
        ///  Sets the callback called when a sweep is received.
        ///
        ///  The callback may be invoked from a background thread, and multiple callback
        ///  invocations may overlap. The `sweep` pointer passed to the callback is only
        ///  valid for the duration of that callback call. `user_data`, if non-NULL, must
        ///  remain valid until the callback is removed or the analyzer is freed.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_spectrum_analyzer_set_sweep_callback", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void rfe_spectrum_analyzer_set_sweep_callback(SpectrumAnalyzer* rfe, delegate* unmanaged[Cdecl]<float*, nuint, ulong, ulong, void*, void> callback, void* user_data);

        /// <summary>
        ///  Removes the sweep callback.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_spectrum_analyzer_remove_sweep_callback", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void rfe_spectrum_analyzer_remove_sweep_callback(SpectrumAnalyzer* rfe);

        /// <summary>
        ///  Sets the callback called when a spectrum analyzer configuration is received.
        ///
        ///  The callback may be invoked from a background thread, and multiple callback
        ///  invocations may overlap. `user_data`, if non-NULL, must remain valid until
        ///  the callback is removed or the analyzer is freed.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_spectrum_analyzer_set_config_callback", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void rfe_spectrum_analyzer_set_config_callback(SpectrumAnalyzer* rfe, delegate* unmanaged[Cdecl]<SpectrumAnalyzerConfig, void*, void> callback, void* user_data);

        /// <summary>
        ///  Removes the configuration callback.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_spectrum_analyzer_remove_config_callback", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void rfe_spectrum_analyzer_remove_config_callback(SpectrumAnalyzer* rfe);

        /// <summary>
        ///  Sets the number of points in each sweep.
        ///
        ///  Only Plus models support changing the sweep length.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_spectrum_analyzer_set_sweep_len", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Result rfe_spectrum_analyzer_set_sweep_len(SpectrumAnalyzer* rfe, ushort sweep_len);

        /// <summary>
        ///  Sets the calculator mode.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_spectrum_analyzer_set_calc_mode", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Result rfe_spectrum_analyzer_set_calc_mode(SpectrumAnalyzer* rfe, CalcMode calc_mode);

        /// <summary>
        ///  Activates the main radio module.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_spectrum_analyzer_activate_main_radio", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Result rfe_spectrum_analyzer_activate_main_radio(SpectrumAnalyzer* rfe);

        /// <summary>
        ///  Activates the expansion radio module.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_spectrum_analyzer_activate_expansion_radio", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Result rfe_spectrum_analyzer_activate_expansion_radio(SpectrumAnalyzer* rfe);

        /// <summary>
        ///  Sets the spectrum analyzer input stage.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_spectrum_analyzer_set_input_stage", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Result rfe_spectrum_analyzer_set_input_stage(SpectrumAnalyzer* rfe, InputStage input_stage);

        /// <summary>
        ///  Sets the amplitude offset in dB.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_spectrum_analyzer_set_offset_db", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Result rfe_spectrum_analyzer_set_offset_db(SpectrumAnalyzer* rfe, sbyte offset_db);

        /// <summary>
        ///  Sets the DSP mode.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "rfe_spectrum_analyzer_set_dsp_mode", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Result rfe_spectrum_analyzer_set_dsp_mode(SpectrumAnalyzer* rfe, DspMode dsp_mode);


    }

    /// <summary>
    ///  Signal generator configuration.
    ///
    ///  Frequencies are represented in hertz. Durations are represented in
    ///  milliseconds.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct SignalGeneratorConfig
    {
        /// <summary>
        ///  Start frequency for frequency sweep and tracking modes.
        /// </summary>
        public ulong start_hz;
        /// <summary>
        ///  CW frequency.
        /// </summary>
        public ulong cw_hz;
        /// <summary>
        ///  Total number of sweep or tracking steps.
        /// </summary>
        public uint total_steps;
        /// <summary>
        ///  Frequency increment per step.
        /// </summary>
        public ulong step_hz;
        /// <summary>
        ///  CW and frequency sweep attenuation setting.
        /// </summary>
        public Attenuation attenuation;
        /// <summary>
        ///  CW and frequency sweep power level.
        /// </summary>
        public PowerLevel power_level;
        /// <summary>
        ///  Number of amplitude sweep power steps.
        /// </summary>
        public ushort sweep_power_steps;
        /// <summary>
        ///  Amplitude sweep start attenuation setting.
        /// </summary>
        public Attenuation start_attenuation;
        /// <summary>
        ///  Amplitude sweep start power level.
        /// </summary>
        public PowerLevel start_power_level;
        /// <summary>
        ///  Amplitude sweep stop attenuation setting.
        /// </summary>
        public Attenuation stop_attenuation;
        /// <summary>
        ///  Amplitude sweep stop power level.
        /// </summary>
        public PowerLevel stop_power_level;
        /// <summary>
        ///  RF output power state.
        /// </summary>
        public RfPower rf_power;
        /// <summary>
        ///  Delay between sweep steps.
        /// </summary>
        public ulong sweep_delay_ms;
    }

    /// <summary>
    ///  Signal generator amplitude sweep configuration.
    ///
    ///  Frequencies are represented in hertz. Durations are represented in
    ///  milliseconds.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct SignalGeneratorConfigAmpSweep
    {
        /// <summary>
        ///  CW frequency used during the amplitude sweep.
        /// </summary>
        public ulong cw_hz;
        /// <summary>
        ///  Number of power steps in the sweep.
        /// </summary>
        public ushort sweep_power_steps;
        /// <summary>
        ///  Starting attenuation setting.
        /// </summary>
        public Attenuation start_attenuation;
        /// <summary>
        ///  Starting output power level.
        /// </summary>
        public PowerLevel start_power_level;
        /// <summary>
        ///  Stopping attenuation setting.
        /// </summary>
        public Attenuation stop_attenuation;
        /// <summary>
        ///  Stopping output power level.
        /// </summary>
        public PowerLevel stop_power_level;
        /// <summary>
        ///  RF output power state.
        /// </summary>
        public RfPower rf_power;
        /// <summary>
        ///  Delay between amplitude sweep steps.
        /// </summary>
        public ulong sweep_delay_ms;
    }

    /// <summary>
    ///  Signal generator CW configuration.
    ///
    ///  Frequencies are represented in hertz.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct SignalGeneratorConfigCw
    {
        /// <summary>
        ///  CW frequency.
        /// </summary>
        public ulong cw_hz;
        /// <summary>
        ///  Total number of configured steps.
        /// </summary>
        public uint total_steps;
        /// <summary>
        ///  Frequency increment per step.
        /// </summary>
        public ulong step_freq_hz;
        /// <summary>
        ///  RF output attenuation setting.
        /// </summary>
        public Attenuation attenuation;
        /// <summary>
        ///  RF output power level.
        /// </summary>
        public PowerLevel power_level;
        /// <summary>
        ///  RF output power state.
        /// </summary>
        public RfPower rf_power;
    }

    /// <summary>
    ///  Signal generator frequency sweep configuration.
    ///
    ///  Frequencies are represented in hertz. Durations are represented in
    ///  milliseconds.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct SignalGeneratorConfigFreqSweep
    {
        /// <summary>
        ///  Start frequency.
        /// </summary>
        public ulong start_hz;
        /// <summary>
        ///  Total number of sweep steps.
        /// </summary>
        public uint total_steps;
        /// <summary>
        ///  Frequency increment per step.
        /// </summary>
        public ulong step_hz;
        /// <summary>
        ///  RF output attenuation setting.
        /// </summary>
        public Attenuation attenuation;
        /// <summary>
        ///  RF output power level.
        /// </summary>
        public PowerLevel power_level;
        /// <summary>
        ///  RF output power state.
        /// </summary>
        public RfPower rf_power;
        /// <summary>
        ///  Delay between sweep steps.
        /// </summary>
        public ulong sweep_delay_ms;
    }

    /// <summary>
    ///  Spectrum analyzer configuration.
    ///
    ///  Frequencies are represented in hertz. Fields that are optional in the Rust
    ///  API use zero or the enum default when the device has not reported a value.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct SpectrumAnalyzerConfig
    {
        /// <summary>
        ///  Sweep start frequency.
        /// </summary>
        public ulong start_freq_hz;
        /// <summary>
        ///  Frequency step between sweep points.
        /// </summary>
        public ulong step_size_hz;
        /// <summary>
        ///  Sweep stop frequency.
        /// </summary>
        public ulong stop_freq_hz;
        /// <summary>
        ///  Sweep center frequency.
        /// </summary>
        public ulong center_freq_hz;
        /// <summary>
        ///  Sweep span.
        /// </summary>
        public ulong span_hz;
        /// <summary>
        ///  Top displayed amplitude in dBm.
        /// </summary>
        public short max_amp_dbm;
        /// <summary>
        ///  Bottom displayed amplitude in dBm.
        /// </summary>
        public short min_amp_dbm;
        /// <summary>
        ///  Number of points in each sweep.
        /// </summary>
        public ushort sweep_len;
        /// <summary>
        ///  Whether the expansion radio module is active.
        /// </summary>
        [MarshalAs(UnmanagedType.U1)] public bool is_expansion_radio_module_active;
        /// <summary>
        ///  Current operating mode.
        /// </summary>
        public Mode mode;
        /// <summary>
        ///  Minimum supported frequency.
        /// </summary>
        public ulong min_freq_hz;
        /// <summary>
        ///  Maximum supported frequency.
        /// </summary>
        public ulong max_freq_hz;
        /// <summary>
        ///  Maximum supported span.
        /// </summary>
        public ulong max_span_hz;
        /// <summary>
        ///  Resolution bandwidth, or zero if it has not been reported by the device.
        /// </summary>
        public ulong rbw_hz;
        /// <summary>
        ///  Amplitude offset in dB, or zero if it has not been reported by the device.
        /// </summary>
        public sbyte amp_offset_db;
        /// <summary>
        ///  Calculator mode, or the default value if it has not been reported by the device.
        /// </summary>
        public CalcMode calc_mode;
    }


    /// <summary>
    ///  Result code returned by fallible `rfe-ffi` functions.
    /// </summary>
    internal enum Result : uint
    {
        /// <summary>
        ///  The function completed successfully.
        /// </summary>
        Success = 0,
        /// <summary>
        ///  The connected device reported unsupported or incompatible firmware.
        /// </summary>
        IncompatibleFirmwareError,
        /// <summary>
        ///  An argument was invalid, such as an out-of-range value or undersized buffer.
        /// </summary>
        InvalidInputError,
        /// <summary>
        ///  The requested operation is not valid for the current device state.
        /// </summary>
        InvalidOperationError,
        /// <summary>
        ///  A serial port or operating system I/O error occurred.
        /// </summary>
        IoError,
        /// <summary>
        ///  The requested data has not been received from the device.
        /// </summary>
        NoData,
        /// <summary>
        ///  A required pointer argument was `NULL`.
        /// </summary>
        NullPtrError,
        /// <summary>
        ///  The device did not respond before the operation timed out.
        /// </summary>
        TimeoutError,
    }

    /// <summary>
    ///  Signal generator model reported by the RF Explorer.
    /// </summary>
    internal enum SignalGeneratorModel : byte
    {
        /// <summary>
        ///  Main 6 GHz signal generator module.
        /// </summary>
        Rfe6Gen = 60,
        /// <summary>
        ///  Expansion 6 GHz signal generator module.
        /// </summary>
        Rfe6GenExpansion = 61,
    }

    /// <summary>
    ///  RF Explorer spectrum analyzer model.
    /// </summary>
    internal enum SpectrumAnalyzerModel : byte
    {
        /// <summary>
        ///  433M model.
        /// </summary>
        Rfe433M = 0,
        /// <summary>
        ///  868M model.
        /// </summary>
        Rfe868M = 1,
        /// <summary>
        ///  915M model.
        /// </summary>
        Rfe915M = 2,
        /// <summary>
        ///  WSUB1G model.
        /// </summary>
        RfeWSub1G = 3,
        /// <summary>
        ///  2.4G model.
        /// </summary>
        Rfe24G = 4,
        /// <summary>
        ///  WSUB3G model.
        /// </summary>
        RfeWSub3G = 5,
        /// <summary>
        ///  6G model.
        /// </summary>
        Rfe6G = 6,
        /// <summary>
        ///  WSUB1G+ model.
        /// </summary>
        RfeWSub1GPlus = 10,
        /// <summary>
        ///  Pro Audio model.
        /// </summary>
        RfeProAudio = 11,
        /// <summary>
        ///  2.4G+ model.
        /// </summary>
        Rfe24GPlus = 12,
        /// <summary>
        ///  4G+ model.
        /// </summary>
        Rfe4GPlus = 13,
        /// <summary>
        ///  6G+ model.
        /// </summary>
        Rfe6GPlus = 14,
        /// <summary>
        ///  MW5G 3 GHz model.
        /// </summary>
        RfeMW5G3G = 16,
        /// <summary>
        ///  MW5G 4 GHz model.
        /// </summary>
        RfeMW5G4G = 17,
        /// <summary>
        ///  MW5G 5 GHz model.
        /// </summary>
        RfeMW5G5G = 18,
        /// <summary>
        ///  Unknown or unsupported model.
        /// </summary>
        Unknown = 19,
    }


}
